language: cpp
compiler: clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake libc++-dev clang
    - cmake --version
    - clang --version
script: mkdir build && cd build/ && cmake ../ && make
