language: cpp
compiler: clang
before_install:
    - sudo apt-get update -qq
    - cmake --version
    - sudo apt-get install -qq cmake
    - cmake --version
    - sudo apt-get install -qq libc++-dev
script: mkdir build && cd build/ && cmake ../ && make
